### PR TITLE
Full path for zpool

### PR DESCRIPTION
**Pull request by sonicaj**
This commit makes sure we use `/sbin/zpool` for zpool subprocess commands.
Ticket: #75387

### CODE REVIEW

**Review by themylogin — COMMENTED** [review]
Is there two `zpool` binaries In FreeBSD 12?

**Comment by sonicaj** [comment]
@themylogin I am not sure,
`which zpool` shows up empty at the point installation is going on. Rest of the commands work fine. including zfs. However both are present under `/sbin/`. Any suggestions on what might be a better way to tackle this ?

**Comment by themylogin** [comment]
@sonicaj does `PATH` include `/sbin`?

**Comment by sonicaj** [comment]
@themylogin yes, that indeed was the issue. I opened up a PR yesterday in trueos for this. Thank you for pointing it out 😀

**Pull request closed without merging**
